version: '3'

services:

  avdc:
    image: ghcr.io/xjasonlyu/avdc:latest
    environment:
      - HTTP_PROXY=http://192.168.1.1:1080
      - HTTPS_PROXY=http://192.168.1.1:1080
    ports:
      - 5000:5000
    volumes:
      - ./avdc.db:/avdc.db
    network_mode: bridge
    restart: unless-stopped
    container_name: avdc
