version: '3'

services:

  avdc:
    image: ghcr.io/xjasonlyu/avdc:latest
    ports:
      - 5000:5000
    volumes:
      - ./avdc.db:/avdc.db
    network_mode: bridge
    restart: unless-stopped
    container_name: avdc
